roupa/urls.py
from django.urls import path
from roupa.views import RoupaListView, RoupaDetailView, RoupaCreateView, RoupaUpdateView, RoupaDeleteView

urlpatterns = [
    path('', RoupaListView.as_view(), name='roupa_list'),
    path('<int:pk>/', RoupaDetailView.as_view(), name='roupa_detail'),
    path('create/', RoupaCreateView.as_view(), name='roupa_create'),
    path('<int:pk>/edit/', RoupaUpdateView.as_view(), name='roupa_update'),
    path('<int:pk>/delete/', RoupaDeleteView.as_view(), name='roupa_delete'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from setup import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('materiais/', include('material.urls')),
    path('movimentacao/', include('movimentacao.urls')),
    path('producao/', include('producao.urls')),
    path('roupas/', include('roupa.urls')),
    path('usuario/', include('usuario.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario.views import UserPasswordChangeView, UserProfileView, UserProfileUpdateView

urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/password/', UserPasswordChangeView.as_view(), name='password_change'),
]

material/models.py
from django.db import models
from django.db.models import Sum, F
from django.apps import apps

from roupa.models import RoupaMaterial  # Importação para carregar modelos dinamicamente

class Material(models.Model):
    nome = models.CharField(verbose_name="Nome", max_length=100, null=False, blank=False)
    descricao = models.TextField(verbose_name="Descrição", null=True, blank=True)
    unid_medida = models.CharField(verbose_name="Unidade de Medida", max_length=30, null=False, blank=True)
    valor = models.DecimalField(verbose_name="Valor", null=False, blank=False, max_digits=10, decimal_places=2)
    imagem = models.ImageField(upload_to="fotos/")

    def __str__(self) -> str:
        return self.nome

    def estoque_atual(self):
    # Importar os modelos necessários
        Movimentacao = apps.get_model('movimentacao', 'Movimentacao')
        RoupaMaterial = apps.get_model('roupa', 'RoupaMaterial')
        Producao = apps.get_model('producao', 'Producao')

    # Soma de todas as movimentações (entradas de estoque)
        movimentacao_estoque = Movimentacao.objects.filter(codigo_material=self).aggregate(Sum  ('quantidade'))
        estoque_movimentacao = movimentacao_estoque['quantidade__sum'] or 0

    # Soma de todas as produções que utilizaram o material
    # Multiplicando a quantidade da produção pela quantidade de material usado em cada roupa
        producao_estoque = RoupaMaterial.objects.filter(
        material=self,
        roupa__in=Producao.objects.values_list('roupa', flat=True)  # Apenas roupas que foram produzidas
        ).annotate(
        material_usado=F('quantidade') * F('roupa__producao__quantidade')  # Multiplicar pela quantidade produzida
         ).aggregate(total_material_usado=Sum('material_usado'))

    # Soma da quantidade de material usada nas produções de roupas
        estoque_producao = producao_estoque['total_material_usado'] or 0

    # Calcula o estoque atual: entradas - saídas
        return estoque_movimentacao - estoque_producao

movimentacao/models.py
from django.db import models
from material.models import Material


# Create your models here.
class Movimentacao(models.Model):
    codigo_material = models.ForeignKey(Material, on_delete = models.CASCADE, verbose_name="Nome", null= False, blank= False)
    quantidade = models.DecimalField(verbose_name="Quantidade", null=True, blank=True, max_digits=10, decimal_places=2)
    data = models.DateField()
    valor_total = models.DecimalField(verbose_name="Valor Total",max_digits=10, decimal_places=2)

    def save(self, *args, **kwargs):
        if self.quantidade and self.valor_total:
            material = self.codigo_material
            material.valor = self.valor_total / self.quantidade
            material.save()
        
        super().save(*args, **kwargs)

producao/models.py
from django.db import models
from roupa.models import Roupa

# Create your models here.
class Producao(models.Model):
    roupa = models.ForeignKey(Roupa, on_delete= models.CASCADE)
    quantidade = models.IntegerField()
    data = models.DateField()
    valorTotal = models.DecimalField(verbose_name="Valor Total da Venda", max_digits=10, decimal_places=2)

usuario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    linguagem = [
        ('pt-br', 'Português - Brasil'),
        ('eng', 'Inglês (Indisponível)')
    ]

    cpf = models.CharField(max_length=11, unique=True, verbose_name="CPF")
    # profile_picture = models.ImageField(upload_to='fotos/', null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    idioma = models.CharField(verbose_name="Idioma", null=False, blank=False,  choices=linguagem, default='pt-br', max_length=7)

    def __str__(self):
        return self.username

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import CustomUser

class CustomUserUpdateForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'cpf', 'profile_picture', 'idioma']

usuario/views.py
from pyexpat.errors import messages
from django.views.generic import DetailView, UpdateView
from django.urls import reverse_lazy
from .models import CustomUser
from .forms import CustomUserUpdateForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin

class UserProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'usuario/profile_detail.html'
    context_object_name = 'user'

    def get_object(self):
        return self.request.user  # Retorna o usuário logado


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'usuario/profile_update.html'
    success_url = reverse_lazy('profile')

    def get_object(self):
        return self.request.user 

class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/password_change.html'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        messages.success(self.request, 'Senha alterada com sucesso!')
        return super().form_valid(form)

usuario/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Phoenix</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'material_list' %}">Material</a>
                    </li>

                    <li> <a class="nav-link active" aria-current="page" href="{% url 'roupa_list' %}">Roupas</a></li>

                    <li> <a class="nav-link active" aria-current="page" href="{% url 'movimentacao_list' %}">Movimentação</a></li>

                    <li> <a class="nav-link active" aria-current="page" href="{% url 'producao_list' %}">Produção</a></li>
                    
                    <li> <a class="nav-link active" aria-current="page" href="{% url 'usuario_list' %}" <img src="..." class="rounded mx-auto d-block" alt="...">>Empresa</a></li>
                    </ul>
                    </ul>
            </div>
        </div>
    </nav>

    <div class="container py-3 px-3">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>