roupa/urls.py
from django.urls import path
from roupa.views import RoupaListView, RoupaDetailView, RoupaCreateView, RoupaUpdateView, RoupaDeleteView

urlpatterns = [
    path('', RoupaListView.as_view(), name='roupa_list'),
    path('<int:pk>/', RoupaDetailView.as_view(), name='roupa_detail'),
    path('create/', RoupaCreateView.as_view(), name='roupa_create'),
    path('<int:pk>/edit/', RoupaUpdateView.as_view(), name='roupa_update'),
    path('<int:pk>/delete/', RoupaDeleteView.as_view(), name='roupa_delete'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from setup import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('materiais/', include('material.urls')),
    path('movimentacao/', include('movimentacao.urls')),
    path('producao/', include('producao.urls')),
    path('roupas/', include('roupa.urls')),
    path('usuario/', include('usuario.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario.views import UserPasswordChangeView, UserProfileView, UserProfileUpdateView

urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/password/', UserPasswordChangeView.as_view(), name='password_change'),
]

usuario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    linguagem = [
        ('pt-br', 'Português - Brasil'),
        ('eng', 'Inglês (Indisponível)')
    ]

    cpf = models.CharField(max_length=11, unique=True, verbose_name="CPF")
    # profile_picture = models.ImageField(upload_to='fotos/', null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    idioma = models.CharField(verbose_name="Idioma", null=False, blank=False,  choices=linguagem, default='pt-br', max_length=7)

    def __str__(self):
        return self.username

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import CustomUser

class CustomUserUpdateForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'cpf', 'profile_picture', 'idioma']

usuario/views.py
from pyexpat.errors import messages
from django.views.generic import DetailView, UpdateView
from django.urls import reverse_lazy
from .models import CustomUser
from .forms import CustomUserUpdateForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin

class UserProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'usuario/profile_detail.html'
    context_object_name = 'user'

    def get_object(self):
        return self.request.user  # Retorna o usuário logado


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'usuario/profile_update.html'
    success_url = reverse_lazy('profile')

    def get_object(self):
        return self.request.user 

class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/password_change.html'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        messages.success(self.request, 'Senha alterada com sucesso!')
        return super().form_valid(form)

usuario/templates/usuario/password_change.html
{% extends 'base.html' %}

{% block title %}Perfil da empresa{% endblock %}

{% block content %}

<h1>Alterar Senha</h1>
    
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit" class="btn btn-dark">Alterar Senha</button>
</form>

<a href="{% url 'profile' %}">Voltar ao Perfil</a>

{% endblock %}

usuario/templates/usuario/profile_detail.html
{% extends 'base.html' %}

{% block title %}Perfil da empresa{% endblock %}

{% block content %}
    {% comment %}
    <h1>Perfil de {{ user.username }}</h1>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>CPF:</strong> {{ user.cpf }}</p>
    <p><strong>Idioma:</strong> {{ user.get_idioma_display }}</p>
    
    {% if user.profile_picture %}
        <img src="{{ user.profile_picture.url }}" alt="Foto de Perfil" style="max-width: 150px;">
    {% else %}
        <p>Sem foto de perfil.</p>
    {% endif %}

    <a href="{% url 'profile_edit' %}">Editar Perfil</a>
    {% endcomment %}

    <div class="alert alert-secondary" role="alert">
        <h2><strong>Perfil de {{ user.username }}</strong></h2>
    </div>

    <ul class="list-group">
        <li class="list-group-item"><p><strong>Email:</strong> {{ user.email }}</p></li>
        <li class="list-group-item"><p><strong>CPF:</strong> {{ user.cpf }}</p></li>
        <li class="list-group-item"><p><strong>Idioma:</strong> {{ user.get_idioma_display }}</p></li>
        {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}" alt="Foto de Perfil" style="max-width: 150px;">
        {% else %}
            <p>Sem foto de perfil.</p>
        {% endif %}
    </ul>

    <div class="d-inline-flex gap-1">
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-dark">Logout</button>
        </form>

        <a type="button" href="{% url 'profile_edit' %}" class="btn btn-dark"><strong>Editar Perfil</strong></a>
    </div>
{% endblock %}

usuario/templates/usuario/profile_update.html
{% extends 'base.html' %}

{% block title %}Edição do perfil{% endblock %}

{% block content %}
    {% comment %}
    <h1>Editar Perfil de {{ user.username }}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

       
    </form>

    <a href="{% url 'profile' %}">Voltar para o Perfil</a>
    {% endcomment %}

    <div class="alert alert-secondary" role="alert">
        <h2><strong>Editar Perfil de {{ user.username }}</strong></h2>
    </div>

    <ul class="list-group">
        <li class="list-group-item">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
    
            <a type="button" href="{% url 'profile' %}" class="btn btn-outline-dark"><strong>Voltar para o Perfil</strong></a>

            <button type="submit" class="btn btn-dark"><b>Salvar Alterações</b></button>
            </form>
        </li>
      </ul>
{% endblock %}